YourTrainerApp2/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using YourTrainerApp2.Models;

namespace YourTrainerApp2.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Index()
        {
            var Post1 = new Blog();
            Post1.Category = "Kategoria wpisu";
            Post1.Title = "Tytuł posta";
            Post1.Users = new List<string> { "użytkownik1", "użytkownik2", "użytkownik3", "użytkownik4" };
            Post1.Comments = new List<string> { "wpis1", "wpis2", "wpis3", "wpis4" };

            return View(Post1);
        }
    }
}

YourTrainerApp2/Controllers/HomeController.cs
using ExerciseAPI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics;
using YourTrainerApp2.Models;
using Exercise = YourTrainerApp2.Models.Exercise;

namespace YourTrainerApp2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IHttpClientFactory _client;

        public HomeController(IHttpClientFactory client, ILogger<HomeController> logger)
        {
			_client = client;
			_logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var client = _client.CreateClient();
            var url = "https://localhost:7051/api/ExerciseAPI/1";

            var response = await client.GetAsync(url);

            var content = await response.Content.ReadAsStringAsync();
            //var result = JsonConvert.DeserializeObject<APIResponse>(content);
            var output = JsonConvert.DeserializeObject<Exercise>(content);

			return View(output);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

YourTrainerApp2/Controllers/TrainingPlanController.cs
using DbDataAccess.Models;
using ExerciseAPI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using YourTrainerApp.Models.DTO;
using YourTrainerApp.Services.IServices;
using YourTrainerApp2.Models;
using YourTrainerApp2.Models.DTO;
using YourTrainerApp2.Services.IServices;

namespace YourTrainerApp2.Controllers
{
    public class TrainingPlanController : Controller
    {
        private readonly ITrainingPlanService _trainingPlanService;
        private readonly ITrainingPlanExerciseService _trainingPlanExerciseService;
        private readonly IExerciseService _exerciseService;

        public TrainingPlanController(ITrainingPlanService trainingPlanService, ITrainingPlanExerciseService trainingPlanExerciseService, IExerciseService exerciseService)
		{
            _trainingPlanService = trainingPlanService;
			_trainingPlanExerciseService = trainingPlanExerciseService;
		    _exerciseService = exerciseService;
        }

        public async Task<IActionResult> Index()
        {
            var apiResponse = await _trainingPlanService.GetAllAsync<APIResponse>();

            var trainingPlans = JsonConvert.DeserializeObject<List<TrainingPlan>>(Convert.ToString(apiResponse.Result))
                                           .Where(tp => tp.Creator == "admin")
                                           .ToList();

            return View(trainingPlans);
        }

        public IActionResult Create()
        {
            return View(new List<string> { "1", "2" });
        }

        public async Task<IActionResult> Show(int id)
        {
			var trainingPlanApiResponse = await _trainingPlanService.GetAsync<APIResponse>(id);

			var trainingPlan = JsonConvert.DeserializeObject<TrainingPlan>(Convert.ToString(trainingPlanApiResponse.Result));
            trainingPlan.CreateTrainingDaysDict();


            return View(trainingPlan);
        }
    }
}

YourTrainerApp2/Areas/Admin/Views/Exercises/Index.cshtml
@model Exercise

<div class="container row">
    <div class="col-2">
        <nav class="navbar-expand-lg">
            <div class="container p-2">
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
                        </svg>
                    </span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav flex-column me-auto">
                        <li class="nav-item dropdown cat_choice" onclick="loadContent('chest')">
                            <a class="nav-link dropdown-item" style="color: white" href="#">Klatka piersiowa</a>
                        </li>

                        <li class="nav-item dropdown cat_choice" onclick="loadContent('back')">
                            <a class="nav-link dropdown-item" style="color: white" href="#">Plecy</a>
                        </li>

                        <li class="nav-item dropdown cat_choice" onclick="loadContent('shoulders')">
                            <a class="nav-link dropdown-item" style="color: white" href="#">Barki</a>
                        </li>

                        <li class="nav-item dropdown cat_choice" onclick="loadContent('triceps')">
                            <a class="nav-link dropdown-item" style="color: white" href="#">Triceps</a>
                        </li>

                        <li class="nav-item dropdown cat_choice" onclick="loadContent('biceps')">
                            <a class="nav-link dropdown-item" style="color: white" href="#">Biceps</a>
                        </li>

                        <li class="nav-item dropdown cat_choice" onclick="loadContent('forearms')">
                            <a class="nav-link dropdown-item" style="color: white" href="#">Przedramiona</a>
                        </li>

                        <li class="nav-item dropdown cat_choice" onclick="loadContent('legs')">
                            @* <a class="nav-link dropdown-item" style="color: #22CE00" href="#">Nogi</a> *@
                            <a class="nav-link dropdown-item" style="color: white" href="#">Nogi</a>
                        </li>

                        <li class="nav-item dropdown cat_choice" onclick="loadContent('abdominals')">
                            @* <a class="nav-link dropdown-item" style="color: #28D770" href="#">Brzuch</a> *@
                            <a class="nav-link dropdown-item" style="color: white" href="#">Brzuch</a>
                        </li>

                        <li class="nav-item dropdown cat_choice" onclick="loadContent('calves')">
                            <a class="nav-link dropdown-item" style="color: white" href="#">Łydki</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </div>

    <div class="col-10" id="testDiv" style="text-align: center; display: flex;">
        <div id="loader" style="display: none;">
            <iframe src="https://gifer.com/embed/ZKZx" width=180 height=180.000 frameBorder="0" allowFullScreen></iframe><p></p>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        // content changes
        var elements = document.querySelectorAll('ul.navbar-nav li.cat_choice');
        // var contents = document.querySelectorAll('.dis');

        elements.forEach(function (element, id) {
            element.addEventListener('click', function () {
                // contents.forEach(function (content) {
                //     content.style.display = 'none';
                // });
                elements.forEach(function (el) {
                    el.style.borderBottom = 'none';
                    el.style.color = 'white'
                })
                elements[id].style.borderBottom = '2px solid green';
                elements[id].style.color = 'green';


            });
        });
    </script>

    <script>
        var images = ["..\\exercises_img\\Ab_Crunch_Machine\\0.jpg", "..\\exercises_img\\Ab_Crunch_Machine\\1.jpg"];
        var currentIndex = 0;

        function changeImage() {
            var img = document.getElementById("imgExer");
            currentIndex = (currentIndex + 1) % images.length;
            // currentIndex = 1;
            img.src = images[currentIndex];
        }

        setInterval(changeImage, 2500);
    </script>

    <script>

        function loadContent(type) {
            $("#loader").show();
            $.ajax({
                url: '/Exercise/GetDynamicContent',
                type: 'GET',
                data: { exerType: type },
                success: function (response) {
                    if (response.length > 0) {
                        var array = response.split(",");
                        var result = document.createElement("div");
                        result.classList.add("row");
                        for (const el of array) {

                            var subArray = el.split("&");

                            var card = document.createElement("div");
                            card.classList.add("card", "my-2");
                            card.style.width = "fit-content";

                            var cardHeader = document.createElement("div");
                            cardHeader.classList.add("card-header");

                            var cardImg = document.createElement("img");
                            cardImg.src = subArray[1];
                            cardImg.alt = "Zdjęcie ćwiczenia";
                            cardImg.style.maxWidth = "300px";

                            cardHeader.appendChild(cardImg);


                            var cardBody = document.createElement("div");
                            cardBody.classList.add("card-body");
                            cardBody.style.height = "95%";

                            var cardTitle = document.createElement("h5");
                            cardTitle.color = "green";
                            cardTitle.classList.add("card-title");

                            var title = document.createElement("a");
                            title.href = "../Exercise/Exercise/" + subArray[2];
                            title.text = subArray[0];
                            title.style.textDecoration = "none";
                            title.color = "green";

                            cardTitle.appendChild(title);

                            cardBody.appendChild(cardTitle);


                            card.appendChild(cardHeader);
                            card.appendChild(cardBody);


                            result.appendChild(card);
                        }
                        $('#loader').hide();
                        $('#testDiv').html(result);
                    }
                    else {
                        $('#loader').hide();
                        $('#testDiv').html('Brak danych');
                    }

                },
                error: function () {
                    alert('Wystąpił błąd pobierania zawartości z bazy danych.');
                }
            })
        }
    </script>
}

YourTrainerApp2/Areas/Visitor/Views/TrainingPlan/Create.cshtml
@using Newtonsoft.Json
@using YourTrainerApp.Models.VM
@inject IHttpContextAccessor httpAcc

@model TrainingPlan 

@{
	//TrainingPlan trainingPlan = JsonConvert.DeserializeObject<TrainingPlan>(httpAcc.HttpContext.Session.GetString("TrainingPlanData"));
	string exercisesInJson = httpAcc.HttpContext.Session.GetString("Exercises");
	List<TrainingPlanExerciseCreateVM> exercises = JsonConvert.DeserializeObject<List<TrainingPlanExerciseCreateVM>>(exercisesInJson);
}
	


<div class="container m-2 d-flex justify-content-center">
	
	<form method="post">
		<div class="text-center">
			<h2>Dodaj nowy plan</h2>
		</div>
		<div>
			<label for="title" class="form-label mt-4">Nazwa planu</label>
			<input name="title" id="title" type="text" class="form-control" value="@Model.Title" onblur="saveTitleData()"/>
		</div>
		<br>
		<div class="btn-group-toggle my-4 d-flex justify-content-center" data-toggle="buttons">
			@foreach (string day in new List<string>() {"Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota", "Niedziela"})
			{
				<label class="btn btn-secondary mx-1 " style="background-color: #262626">
					<input type="checkbox"
						   class="days-checkbox d-none"
						   onclick="saveTrainigDaysData('@day'); changeCheckboxColor(this)"
						   @(Model.TrainingDaysDict[day] ? "checked" : "")>
					@day
				</label>
			}
		</div>
		<br />

		<div>
			<input asp-for="@Model.Creator" value="@httpAcc.HttpContext.Session.GetString("Username")" hidden />
		</div>

		<div class="row">
			<label class="form-label mt-4">Ćwiczenia</label>

			@if (exercises is not null && exercises.Count > 0)
			{
				<div class="row d-flex justify-content-center">
				@for (int i = 0; i < exercises.Count; i++)
				{
					int exerciseId = Model.Exercises[i].EId;
					<div class="card m-2 p-0" style="width: 300px; height: fit-content;">
						<div class="card-header p-0">
							<img src="/@exercises[i].ImgPath1" alt="Alternate Text" style="width: 300px; height: 200.81px" />
						</div>
						<div class="card-body" style="height: 95%">
							<h6 class="card-title text-center">@exercises[i].Name</h6>
							<hr />
							<ol id="ol_@exerciseId">

								@{
									string[] reps = Model.Exercises[i].Reps.Split(";");
									string[] weights = Model.Exercises[i].Weights.Split(";");
								}

								@for (int j = 0; j < Model.Exercises[i].Series; j++)
								{
									if (exercises[i].Equipment == "" || exercises[i].Equipment == "body only" || exercises[i].Equipment == "other")
									{
										<li>
											seria:
											<input class="input_@exerciseId" 
												   id="@j-r-@exerciseId" 
												   type="number" value="@reps[j]" min="1" max="10" 
												   style="width: 50px;" 
												   onblur="saveRepsAndWeightsData(@exerciseId, @j)"/>
											powtórzeń
											<input class="input_@exerciseId" 
												   id="@j-w-@exerciseId"  
												   type="number" value="0" hidden/>
										</li>
									}
									else
									{
										<li>
											seria:
											<input class="input_@exerciseId" 
												   id="@j-r-@exerciseId" 
												   type="number" value="@reps[j]" min="1" max="10" 
												   style="width: 50px;"
												   onblur="saveRepsAndWeightsData(@exerciseId, @j)" />
											 x
											<input class="input_@exerciseId" 
												   id="@j-w-@exerciseId" 
												   type="number" value="@weights[j]" step="2.5" max="500" 
												   style="width: 50px;" 
												   onblur="saveRepsAndWeightsData(@exerciseId, @j)"/>
											kg
										</li>		
									}		
								}
								
							</ol>
							<div class="row d-flex justify-content-center">
								<div class="col-4 btn-group">
									<a class="btn button-red" asp-action="DecrementExerciseSeries" asp-route-id="@exerciseId">-</a>
									<a class="btn button-green" asp-action="IncrementExerciseSeries" asp-route-id="@exerciseId">+</a>	
								</div>
							</div>
						</div>
					</div>
				}
				</div>
			}

			<a class="btn button-green mx-3" type="button" style="width: fit-content"
			   asp-area="Visitor" asp-controller="TrainingPlan" asp-action="ExerciseSelection"> + </a>
		</div>

		<div>
			<label for="notes" class="form-label mt-4">Notatka do planu</label>
			<textarea name="notes" class="form-control" id="notes" type="text" asp-for="@Model.Notes" onblur="saveNotesData()"></textarea>
		</div>

		<br /><br />
		<div>
			<button type="submit" class="btn button-green form-control"
					asp-area="Visitor" asp-controller="TrainingPlan" asp-action="Create" asp-route-trainingPlan="@Model">Zatwierdź</button>

		</div>
	</form>
</div>

@* jQuerry modal popup *@

@section Scripts
{
	<script src="~/js/trainingDataSaving.js"></script>
	<script>

		var checkboxInputs = document.querySelectorAll(".days-checkbox");

		checkboxInputs.forEach(function(checkboxInput) {
			if (checkboxInput.checked) {
				checkboxInput.parentElement.style.color = '#22CE00';
				checkboxInput.parentElement.style.border = '1px solid #22CE00';
			}
			else {
				checkboxInput.parentElement.style.color = '';
				checkboxInput.parentElement.style.border = 'none';
			}
		})

		function changeCheckboxColor(checkbox) {
			if (checkbox.checked) {
				checkbox.parentElement.style.color = '#22CE00';
				checkbox.parentElement.style.border = '1px solid #22CE00';
			} else {
				checkbox.parentElement.style.color = '';
				checkbox.parentElement.style.border = 'none';
			}
		}
	</script>
	<script>
		function displayInputs(id) {
			var inputs = document.getElementsByClassName("input_" + id);

			var values = document.getElementsByClassName("value_" + id);

			for (var i = 0; i < inputs.length; i++) {
				inputs[i].style.display = "inline-block";
				values[i].style.display = "none";
			}
		}

		function hideInputs(id) {
			var inputs = document.getElementsByClassName("input_" + id);

			var values = document.getElementsByClassName("value_" + id);

			for (var i = 0; i < inputs.length; i++) {
				inputs[i].style.display = "none";
				values[i].style.display = "inline-block";
			}
		}

		// function addSeries(id) {
		// 	const htmlCode = '<li>seria: <input class="input_' + id + '" type="number" value="4" max="10" style="width: 50px;" /> x <input class="input_' + id + '" type="number" value="80" max="500" style="width: 50px;" /> kg</li>'

		// 	var ol = document.getElementById("ol_" + id);
		// 	ol.innerHTML += htmlCode;
		// }

		// function removeSeries(id) {
		// 	var ol = document.getElementById("ol_" + id);
		// 	let lastLi = ol.lastChild;

		// 	ol.removeChild(lastLi);

		// }

	</script>



}

YourTrainerApp2/Views/ExercisesSet/Exercise.cshtml
@model Exercise

<div class="mx-5">
	<div class="d-flex">

		<div class="col-8">
			<div class="card my-4">
				<div class="card-header">
					<h3 class="card-title">@Model.Name</h3>
				</div>
				<div class="card-body row">
					<div class="col-6">
						<img class="img-fluid"
							 src="..\..\@Model.ImgPath1"
							 style="" />
					</div>
					<div class="col-6">
						<img class="img-fluid"
							 src="..\..\@Model.ImgPath2"
							 style="" />
					</div>
					<div class="my-3">
						<ol>
						@{
							string[]? instrList = Model.Instructions.Split(";");
						}
						@foreach (string instr in instrList)
						{
							<li>@instr</li>
						}
						</ol>
					</div>
				</div>
			</div>
		</div>
		<div class="col-4 d-flex justify-content-center">
			<div class="card my-4" style="width: fit-content">
				<img src="https://media.istockphoto.com/id/898222860/pl/wektor/m%C4%99skie-cia%C5%82o-cz%C5%82owieka-mapa-mi%C4%99%C5%9Bni-rectus-abdominis.jpg?s=2048x2048&w=is&k=20&c=NXpHy5Pmo42hhbRiRcRGK-kEF_ibBWaiQC-0Y-rbEpo="
						style="width: 200px" />
					
				<div class="card-body">
					<ul>
						<li>Grupa mięśni: @Model.Force</li>
						<li>Poziom: @Model.Level</li>
						<li>Mechanika: @Model.Mechanic</li>
						<li>Wyposażenie: @Model.Equipment</li>
						<li>Główne mięśnie: @Model.PrimaryMuscles</li>
						<li>Mięśnie pomocnicze:
							<ul>
							@foreach (string musc in Model.SecondaryMuscles.Split(";"))
							{
								<li>@musc</li>
							}
							</ul>
						</li>
						<li>Kategoria: @Model.Category</li>

					</ul>
				</div>

			</div>
			<div style="text-align: center">
				
			</div>
			

		</div>
	</div>
</div>