YourTrainer_App/Areas/GymMember/Controllers/DataSettingsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using YourTrainer_App.Areas.GymMember.Services;
using YourTrainer_Utility;
using YourTrainer_App.Models;

namespace YourTrainer_App.Areas.GymMember.Controllers;

[Area("GymMember")]
public class DataSettingsController : Controller
{
	private readonly IMemberDataSettingsService _memberDataSettingsService;
	private int _memberId => int.Parse(HttpContext.Session.GetString("UserId"));

	public DataSettingsController(IMemberDataSettingsService memberDataSettingsService)
	{
		_memberDataSettingsService = memberDataSettingsService;
	}

	[HttpGet]
	[Authorize(Roles = "gym member")]
	public async Task<IActionResult> ShowData()
	{
		if (await _memberDataSettingsService.MemberDataIsPresent(_memberId))
		{
			return View(await _memberDataSettingsService.GetMemberDataFromDb(_memberId));
		}

		return View(_memberDataSettingsService.GetMemberDataDefault(_memberId, HttpContext.Session.GetString("Username")));
	}

	[HttpPost]
	[Authorize(Roles = "gym member")]
	public async Task<IActionResult> ShowData(MemberDataModel memberData)
	{
		if (memberData.TrainersId is null)
		{
			memberData.TrainersId = "0";
		}

		if (memberData.TrainersPlan is null)
		{
			memberData.TrainersPlan = "0";
		}

		if (ModelState.IsValid)
		{
			string errorResponse;
			if (await _memberDataSettingsService.MemberDataIsPresent(_memberId))
			{
				errorResponse = await _memberDataSettingsService.UpdateMemberDataOrGetErrorResponse(memberData);
			}
			else
			{
				errorResponse = await _memberDataSettingsService.CreateMemberDataOrGetErrorResponse(memberData, HttpContext.Session.GetString(StaticDetails.SessionToken));
			}

			if (errorResponse.Length > 0)
			{
				ModelState.AddModelError(string.Empty, errorResponse);
			}
			else
			{
				TempData["success"] = "Zapisano zmiany";
				return RedirectToAction("ShowData");
			}
		}

		return View(memberData);
	}

	[Authorize(Roles = "gym member")]
	public async Task<IActionResult> ClearData()
	{
		await _memberDataSettingsService.ClearMemberData(_memberId, HttpContext.Session.GetString(StaticDetails.SessionToken));
		return RedirectToAction("ShowData");
	}
}

YourTrainer_App/Areas/Trainer/Controllers/DataSettingsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using YourTrainer_App.Areas.Trainer.Services;
using YourTrainer_App.Services.APIServices.IServices;
using YourTrainer_App.Models;

namespace YourTrainer_App.Areas.Trainer.Controllers;

[Area("Trainer")]
public class DataSettingsController : Controller
{
	private readonly ITrainerDataService _trainerDataService;
    private readonly ITrainerDataSettingsService _trainerDataSettingsService;

    private int _trainerId
    {
        get => int.Parse(HttpContext.Session.GetString("UserId"));
    }


	public DataSettingsController(ITrainerDataService trainerDataService, ITrainerDataSettingsService trainerDataSettingsService)
    {
        _trainerDataService = trainerDataService;
        _trainerDataSettingsService = trainerDataSettingsService;
    }

    [HttpGet]
    [Authorize(Roles = "trainer")]
    public async Task<IActionResult> ShowData()
    {
        if (await _trainerDataSettingsService.TrainerDataIsPresent(_trainerId))
        {
            return View(await _trainerDataSettingsService.GetTrainerDataFromDb(_trainerId));
		}

        return View(_trainerDataSettingsService.GetTrainerDataDefault(_trainerId, HttpContext.Session.GetString("Username")));
    }

    [HttpPost]
    [Authorize(Roles = "trainer")]
	public async Task<IActionResult> ShowData(TrainerDataModel trainerData)
    {
        if (ModelState.IsValid) 
        {
		    if (await _trainerDataSettingsService.TrainerDataIsPresent(_trainerId))
            {
                await _trainerDataSettingsService.UpdateTrainerData(trainerData);
            }
            else
            {
			    await _trainerDataSettingsService.CreateTrainerData(trainerData);
		    }

			TempData["success"] = "Zapisano zmiany";
			return RedirectToAction("ShowData");
		}

        return View(trainerData);
    }

	[Authorize(Roles = "trainer")]
	public async Task<IActionResult> ClearData()
    {
        await _trainerDataSettingsService.ClearTrainerData(_trainerId);
        return RedirectToAction("ShowData");
    }
}

YourTrainer_App/Areas/Trainer/Views/DataSettings/ShowData.cshtml
@using YourTrainer_App.Models

@model TrainerDataModel

<div>
	<form method="post">
		<div class="container">
			<div class="m-2">
				<input class="form-control" type="number" asp-for="@Model.TrainerId" hidden />
			</div>
			<div class="m-2">
				<label class="form-label" for="trainerName">Imię</label>
				<input id="trainerName" class="form-control" name="trainerName" type="text" asp-for="@Model.TrainerName" disabled/>
			</div>
			<div class="m-2">
				<label class="form-label" for="description">Twój opis</label>
				<textarea id="description" class="form-control" name="description" type="text" asp-for="@Model.Description" disabled></textarea>
			</div>
			<div class="m-2">
				<label class="form-label" for="email">Email kontaktowy</label>
				<input id="email" class="form-control" name="email" type="text" asp-for="@Model.Email" disabled />
			</div>
			<div class="m-2">
				<label class="form-label" for="phoneNumber">Numer telefonu</label>
				<input id="phoneNumber" class="form-control" name="phoneNumber" type="text" asp-for="@Model.PhoneNumber" disabled />
			</div>
			<div class="m-2">
				<input class="form-control" name="rate" type="number" value="3" asp-for="@Model.Rate" hidden/>
			</div>
			<div class="m-2">
				<input class="form-control" name="membersId" type="text" value="0" asp-for="@Model.MembersId" hidden />
			</div>
			<div class="m-2">
				<label class="form-label" for="availability">Przyjmowanie nowych klientów (0: nie, 1: tak):</label>
				<input id="availability" class="form-control" name="availability" type="number" asp-for="@Model.Availability" disabled />
			</div>
			<div class="d-flex justify-content-between">
				<div class="btn-group">
					<button id="submitButton" class="btn button-green" type="submit" asp-area="Trainer" asp-controller="DataSettings" asp-action="ShowData" hidden>Zatwierdź</button>
					<a id="clearButton" class="btn button-red" asp-area="Trainer" asp-controller="DataSettings" asp-action="ClearData" hidden>Wyczyść</a>
				</div>
				<div>
					<button id="editButton" type="button" class="btn button-orange" onclick="enableInputs()">Edycja</button>
					<button id="removeChangesButton" type="button" class="btn button-orange" onclick="disableInputs()" hidden>Cofnij zmiany</button>
				</div>
			</div>
		</div>
	</form>
</div>

@section Scripts {
	<script>
		function enableInputs() {
			document.getElementById("trainerName").removeAttribute("disabled");
			document.getElementById("description").removeAttribute("disabled");
			document.getElementById("email").removeAttribute("disabled");
			document.getElementById("phoneNumber").removeAttribute("disabled");
			document.getElementById("availability").removeAttribute("disabled");

			document.getElementById("submitButton").removeAttribute("hidden");
			document.getElementById("clearButton").removeAttribute("hidden");
			document.getElementById("removeChangesButton").removeAttribute("hidden");
			document.getElementById("editButton").setAttribute("hidden", "hidden");
		}

		function disableInputs() {
			document.getElementById("trainerName").setAttribute("disabled", "disabled");
			document.getElementById("description").setAttribute("disabled", "disabled");
			document.getElementById("email").setAttribute("disabled", "disabled");
			document.getElementById("phoneNumber").setAttribute("disabled", "disabled");
			document.getElementById("availability").setAttribute("disabled", "disabled");

			document.getElementById("submitButton").setAttribute("hidden", "hidden");
			document.getElementById("clearButton").setAttribute("hidden", "hidden");
			document.getElementById("editButton").removeAttribute("hidden");
			document.getElementById("removeChangesButton").setAttribute("hidden", "hidden");

			location.reload();
		}
	</script>
}