YourTrainer_App/Areas/Admin/Controllers/ExerciseAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using YourTrainer_App.Areas.Admin.Services;
using YourTrainer_Utility;
using YourTrainer_App.Models;
using YourTrainer_App.Models.VM;

namespace YourTrainer_App.Areas.Admin.Controllers;

[Area("Admin")]
public class ExerciseAdminController : Controller
{
	private readonly IExerciseAdminService _exerciseAdminService;

	public ExerciseAdminController(IExerciseAdminService exerciseAdminService)
	{
		_exerciseAdminService = exerciseAdminService;
	}

	[Authorize(Roles = "admin")]
	public async Task<IActionResult> Index()
	{
		List<Exercise> exerciseList = await _exerciseAdminService.GetExercisesList();

		return View(exerciseList);
	}

	[Authorize(Roles = "admin")]
	public IActionResult Create()
	{
		ExerciseCreateVM exerciseCreate = new();
		return View(exerciseCreate);
	}

	[HttpPost]
	[Authorize(Roles = "admin")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ExerciseCreateVM exerciseCreated)
	{
		if (ModelState.IsValid)
		{
			(string, string) createResponse = await _exerciseAdminService.CreateExerciseAndGetResponse(exerciseCreated, HttpContext.Session.GetString(StaticDetails.SessionToken));
			string responseType = createResponse.Item1;
			string responseMessage = createResponse.Item2;
			if (responseType == "Error")
			{
				ModelState.AddModelError(string.Empty, responseMessage);
			}
			else
			{
				TempData["success"] = responseMessage;
				return RedirectToAction("Index");
			}
		}

		ExerciseCreateVM exerciseVM = new();
		exerciseVM.Exercise = exerciseCreated.Exercise;
		
		return View(exerciseVM);
	}

	[Authorize(Roles = "admin")]
    public async Task<IActionResult> Update(int id)
	{
		ExerciseCreateVM exerciseCreateLists = new();
		Exercise exercise = await _exerciseAdminService.GetExercise(id);
		exerciseCreateLists.Exercise = exercise;

		return View(exerciseCreateLists);
	}

	[HttpPost]
	[Authorize(Roles = "admin")]
	public async Task<IActionResult> Update(ExerciseCreateVM exerciseUpdated)
	{
		if (ModelState.IsValid)
		{
			(string, string) updateResponse = await _exerciseAdminService.UpdateExerciseAndGetResponse(exerciseUpdated, HttpContext.Session.GetString(StaticDetails.SessionToken));
			string responseType = updateResponse.Item1;
			string responseMessage = updateResponse.Item2;
			if (responseType == "Error")
			{
				ModelState.AddModelError(string.Empty, responseMessage);
			}
			else
			{
				TempData["success"] = responseMessage;
				return RedirectToAction("Index");
			}
		}

		return View(exerciseUpdated);
	}


	[Authorize(Roles = "admin")]
	public async Task<IActionResult> Delete(int id)
	{
		Exercise exercise = await _exerciseAdminService.GetExercise(id);
		return View(exercise);
	}


    [Authorize(Roles = "admin")]
    [HttpPost, ActionName("Delete")]
	public async Task<IActionResult> DeletePOST(int id)
	{
		if (TempData["success"] is not null)
		{
			TempData["success"] = "";
		}
		(string, string) updateResponse = await _exerciseAdminService.DeleteExerciseAndGetResponse(id, HttpContext.Session.GetString(StaticDetails.SessionToken));
		string responseType = updateResponse.Item1;
		string responseMessage = updateResponse.Item2;
		if (responseType == "Error")
		{
			ModelState.AddModelError(string.Empty, responseMessage);
		}
		else
		{
			TempData["success"] = responseMessage;
			return RedirectToAction("Index");
		}

		return View(id);
	}
}

YourTrainer_App/Areas/Admin/Views/ExerciseAdmin/Create.cshtml
@using YourTrainer_App.Models.VM
@model ExerciseCreateVM


<div class="my-4">
	<div class="py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Stwórz ćwiczenie</h2>
			</div>
		</div>
	</div>
	<div class="p-4">
		<form method="post" asp-action="Create">
			<div class="border p-3 mt-4">
				<div asp-validation-summary="All" class="text-danger"></div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Exercise.Name" class="form-control border-0 shadow" />
					<label asp-for="Exercise.Name" class="ms-2">Nazwa</label>
				</div>
				<div class="form-floating py-2 col-12">
					<select class="form-select" asp-for="Exercise.Force" asp-items="@Model.ForceOptionsList">
						<option selected disabled >--Wybierz typ ćwiczenia</option>
					</select>
					<label asp-for="Exercise.Force" class="ms-2">Typ ćwiczenia</label>
				</div>
				<div class="form-floating py-2 col-12">
					<select class="form-select" asp-for="Exercise.Level" asp-items="@Model.LevelOptionsList">
						<option selected disabled>--Wybierz poziom trudności ćwiczenia</option>
					</select>
					<label asp-for="Exercise.Level" class="ms-2">Poziom trudności</label>
				</div>
				<div class="form-floating py-2 col-12">
					@* <input asp-for="Exercise.Mechanic" class="form-control border-0 shadow" /> *@
					<select class="form-select" asp-for="Exercise.Mechanic" asp-items="@Model.MechanicOptionsList">
						<option selected disabled>--Wybierz--</option>
					</select>
					<label asp-for="Exercise.Mechanic" class="ms-2">Mechanika ćwiczenia</label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Exercise.Equipment" class="form-control border-0 shadow" /> 
					<label asp-for="Exercise.Equipment" class="ms-2">Wyposażenie</label>
				</div>
				<div class="form-floating py-2 col-12">
					@* <input asp-for="Exercise.PrimaryMuscles" class="form-control border-0 shadow" /> *@
					<select class="form-select" asp-for="Exercise.PrimaryMuscles" asp-items="@Model.PrimaryMuscleOptionsList">
						<option selected disabled>--Wybierz--</option>
					</select>
					<label asp-for="Exercise.PrimaryMuscles" class="ms-2">Mięśnie główne</label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Exercise.SecondaryMuscles" class="form-control border-0 shadow" />
					<label asp-for="Exercise.SecondaryMuscles" class="ms-2">Mięśnie pomocnicze</label>
				</div>
				<div class="form-floating py-2 col-12">
					<textarea asp-for="Exercise.Instructions" class="form-control border-0 shadow"></textarea>
					<label asp-for="Exercise.Instructions" class="ms-2">Instrukcje</label>
				</div>
				<div class="form-floating py-2 col-12">
					@* <input asp-for="Exercise.Category" class="form-control border-0 shadow" /> *@
					<select class="form-select" asp-for="Exercise.Category" asp-items="@Model.CategoryOptionsList">
						<option selected disabled>--Wybierz--</option>
					</select>
					<label asp-for="Exercise.Category" class="ms-2">Kategoria</label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Exercise.ImgPath1" class="form-control border-0 shadow" />
					<label asp-for="Exercise.ImgPath1" class="ms-2">Ścieżka do zdjęcia pierwszego</label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Exercise.ImgPath2" class="form-control border-0 shadow" />
					<label asp-for="Exercise.ImgPath2" class="ms-2">Ścieżka do zdjęcia drugiego</label>
				</div>

				<div class="row mt-3">
					<div class="col-6 col-md-3">
						<button type="submit" class="btn btn-danger form-control">Utwórz</button>
					</div>
					<div class="col-6 col-md-3">
						<a asp-controller="ExerciseAdmin" asp-action="Index" class="btn btn-outline-secondary border form-control">
							Wróć do listy
						</a>
					</div>
				</div>


			</div>
		</form>
	</div>
</div>

YourTrainer_App/Areas/Admin/Views/ExerciseAdmin/Delete.cshtml
@model Exercise


<div class="my-4">
	<div class="py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Usuń ćwiczenie</h2>
			</div>
		</div>
	</div>
	<div class="p-4">
		<form method="post">
			<div class="border p-3 mt-4">
				<input asp-for="Id" hidden />
				@*<div asp-validation-summary="All"></div>*@
				<div class="form-floating py-2 col-12">
					<input asp-for="Name" disabled class="form-control border-0 shadow" />
					<label asp-for="Name" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Force" disabled class="form-control border-0 shadow" />
					<label asp-for="Force" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Level" disabled class="form-control border-0 shadow" />
					<label asp-for="Level" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Mechanic" disabled class="form-control border-0 shadow" />
					<label asp-for="Mechanic" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Equipment" disabled class="form-control border-0 shadow" />
					<label asp-for="Equipment" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="PrimaryMuscles" disabled class="form-control border-0 shadow" />
					<label asp-for="PrimaryMuscles" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="SecondaryMuscles" disabled class="form-control border-0 shadow" />
					<label asp-for="SecondaryMuscles" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Instructions" disabled class="form-control border-0 shadow" />
					<label asp-for="Instructions" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Category" disabled class="form-control border-0 shadow" />
					<label asp-for="Category" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="ImgPath1" disabled class="form-control border-0 shadow" />
					<label asp-for="ImgPath1" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="ImgPath2" disabled class="form-control border-0 shadow" />
					<label asp-for="ImgPath2" class="ms-2"></label>
				</div>

				<div class="row mt-3">
					<div class="col-6 col-md-3">
						<button type="submit" class="btn btn-danger form-control">Usuń</button>
					</div>
					<div class="col-6 col-md-3">
						<a asp-controller="ExerciseAdmin" asp-action="Index" class="btn btn-outline-secondary border form-control">
							Wróć do listy
						</a>
					</div>
				</div>


			</div>
		</form>
	</div>
</div>

YourTrainer_App/Areas/Admin/Views/ExerciseAdmin/Index.cshtml
@model List<Exercise>

<div class="my-4">
	<div class="py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Lista ćwiczeń</h2>
			</div>
		</div>
	</div>
	<div class="p-4">
		<div class="row pb-3">
			<div class="col-8"></div>
			<div class="col-4 text-end">
				<a asp-controller="ExerciseAdmin" asp-action="Create" class="btn button-green">
					Dodaj nowe ćwiczenie <i class="bi bi-plus"></i>
				</a>
			</div>
		</div>

		<table style="border-collapse: separate; border-spacing: 0 20px;">
			<tr>
				<thead>
					<th class="w-25">Nazwa</th>
					<th class="w-20">Zdjęcie 1</th>
					<th class="w-20">Zdjęcie 2</th>
					<th>Edycja/Usuń</th>
				</thead>
			</tr>
			<tr>
				<tbody>
					@foreach (var obj in Model)
					{
						<tr>
							<td>@obj.Name</td>
							<td>
								<img src="..\@obj.ImgPath1" width="75%"
									 style="border-radius: 5px; border: 1px solid #bbb9b9" />
							</td>
							<td>
								<img src="..\@obj.ImgPath2" width="75%"
										 style="border-radius: 5px; border: 1px solid #bbb9b9" />
							</td>
							<td>
								<div class="w-75 btn-group" role="group">
									<a asp-controller="ExerciseAdmin" asp-action="Update" asp-route-id="@obj.Id" class="btn button-orange">
										<i class="bi bi-pencil-square"></i> Edit
									</a>
									<a asp-controller="ExerciseAdmin" asp-action="Delete" asp-route-id="@obj.Id" class="btn button-red">
										<i class="bi bi-trash-fill"></i> Delete
									</a>
								</div>
							</td>
						</tr>
						@* <hr /> *@
					}
				</tbody>
			</tr>
		</table>

	</div>
</div>

YourTrainer_App/Areas/Admin/Views/ExerciseAdmin/Update.cshtml
@using YourTrainer_App.Models.VM
@model ExerciseCreateVM

<div class="my-4">
	<div class="py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Aktualizuj ćwiczenie</h2>
			</div>
		</div>
	</div>
	<div class="p-4">
		<form method="post" asp-action="Update">
			<div class="border p-3 mt-4">
				<input asp-for="Exercise.Id" hidden />
				<div asp-validation-summary="All" class="text-danger"></div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Exercise.Name" class="form-control border-0 shadow" />
					<label asp-for="Exercise.Name" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					@* <input asp-for="Force" class="form-control border-0 shadow" /> *@
					<select class="form-select" asp-for="Exercise.Force" asp-items="@Model.ForceOptionsList">
						<option selected disabled>--Wybierz typ ćwiczenia</option>
					</select>
					<label asp-for="Exercise.Force" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					<select class="form-select" asp-for="Exercise.Level" asp-items="@Model.LevelOptionsList">
						<option selected disabled>--Wybierz poziom trudności ćwiczenia</option>
					</select>
					@* <input asp-for="Exercise.Level" class="form-control border-0 shadow" /> *@
					<label asp-for="Exercise.Level" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					@* <input asp-for="Exercise.Mechanic" class="form-control border-0 shadow" /> *@
					<select class="form-select" asp-for="Exercise.Mechanic" asp-items="@Model.MechanicOptionsList">
						<option selected disabled>--Wybierz--</option>
					</select>
					<label asp-for="Exercise.Mechanic" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Exercise.Equipment" class="form-control border-0 shadow" />
					<label asp-for="Exercise.Equipment" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					@* <input asp-for="Exercise.PrimaryMuscles" class="form-control border-0 shadow" /> *@
					<select class="form-select" asp-for="Exercise.PrimaryMuscles" asp-items="@Model.PrimaryMuscleOptionsList">
						<option selected disabled>--Wybierz--</option>
					</select>
					<label asp-for="Exercise.PrimaryMuscles" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Exercise.SecondaryMuscles" class="form-control border-0 shadow" />
					<label asp-for="Exercise.SecondaryMuscles" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Exercise.Instructions" class="form-control border-0 shadow" />
					<label asp-for="Exercise.Instructions" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					@* <input asp-for="Exercise.Category" class="form-control border-0 shadow" /> *@
					<select class="form-select" asp-for="Exercise.Category" asp-items="@Model.CategoryOptionsList">
						<option selected disabled>--Wybierz--</option>
					</select>
					<label asp-for="Exercise.Category" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Exercise.ImgPath1" class="form-control border-0 shadow" />
					<label asp-for="Exercise.ImgPath1" class="ms-2"></label>
				</div>
				<div class="form-floating py-2 col-12">
					<input asp-for="Exercise.ImgPath2" class="form-control border-0 shadow" />
					<label asp-for="Exercise.ImgPath2" class="ms-2"></label>
				</div>

				<div class="row mt-3">
					<div class="col-6 col-md-3">
						<button type="submit" class="btn btn-danger form-control">Aktualizuj</button>
					</div>
					<div class="col-6 col-md-3">
						<a asp-controller="ExerciseAdmin" asp-action="Index" class="btn btn-outline-secondary border form-control">
							Wróć do listy
						</a>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>